### ISSUE TITLE
Run attention selector during proactive tagging

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#42]
Attention selector should run in the demo, so the iCub appears more alive .. :).

This comes with the problem that some objects might disappear from the view.

**Comment by maxime-petit** [comment]
@Inserm the FPS for the IOL is 10 FPS, so it might not be so much of a big issue under "normal" GPU CUDA optimisation for the "smoothness". 

However, we have to implement a small "searching" behavior if the robot is just looking to 1/2 object because the 3rd one is none visible when looking the others

**Comment by Tobias-Fischer** [comment]
I guess it would be a good idea if someone from a lab with the cluster is taking care of this, so we have similar conditions to what we will have in Lyon.

**Comment by clement-moulin-frier** [comment]
We are currently running Attention Selector during the proactive demo and it works quite well (the robot indeed appears much more alive).  The only problem is that when pointing at objects, the robot can sometime look at another one. What would be the best way to focus the attention of the robot on the object it is pointing? By increasing its saliency through Pasar? If so, is Attention Selector able to read the saliency values set by Pasar to prioritize where it is looking?

PS: Note that we are currently working with a pre-populated OPC, so we do not run IOL and colleagues.

**Comment by pattacini** [comment]
Hi @clement-moulin-frier 

Actually, if the `point` is performed via `ARE`, the handling of attention should be already taken into account: see [[1]] and [[2]].

Could you check that the connection between the two sub-system is in place?

[1]: https://github.com/robotology/wysiwyd/blob/master/main%2Fsrc%2Flibraries%2Fwrdac%2Finclude%2Fwrdac%2Fsubsystems%2FsubSystem_ARE.h#L329
[2]: https://github.com/robotology/wysiwyd/blob/master/main%2Fsrc%2Flibraries%2Fwrdac%2Finclude%2Fwrdac%2Fsubsystems%2FsubSystem_ARE.h#L67

**Comment by gregoire-pointeau** [comment]
However, increasing the salience of the pointed object is mandatory I would say: if you point to an object, its salience should increase.
However you don't need to go through `pasar` to do it, a simple `opcClient` is enough.
Maybe in the `susystem_ARE` we could had to increase the salience of the pointed object. I'll look at it.
(increase the salience is needed independently from the problem of the `attentionSelector`)

**Comment by pattacini** [comment]
@gregoire-pointeau don't mix things: `SubSystem_ARE` is for controlling the robot movements, so it's a very very ... very very bad location where to deal with object salience ;)

**Comment by pattacini** [comment]
Salience handling should be running somewhere in our architecture with the aim to provide the robot with some points of interest (POI) where to focus the attention.

Once a POI gets selected, `SubSystem_ARE` kicks in and should prevent `attentionSelector` to redirect the gaze elsewhere for the entire duration of the point action.

**Comment by gregoire-pointeau** [comment]
I disagree a bit. `ARE` is for controlling the robot, where the `subsystem_ARE` is just something to link `ARE` and the `WR` environment.
This is why for me the `subsystems` are for the `WR` related.
I don't see why the `subsystem_ARE` couldn't handle the salience.

**Comment by pattacini** [comment]
`SubSystem_ARE` is a mere interface to `ARE`, so please don't put anything related to salience therein: it's really against software engineering rules.

The salience of an object has nothing to do with the robot movements: let's not mix inputs to the motor control with motor control itself.

**Comment by maxime-petit** [comment]
Gregoire you said that if you point to an object, its salience should increase, that is how you motivate `ARE` or `subsystem_ARE`to be involved in the saliency. But for me it is actually the opposite: you point an object because the saliency is already high. The saliency cause your pointing, so the saliency should be high BEFORE you do the pointing: that is why you point this precise object and not another one. The pointing of another agent however, cause the saliency.

In proactive, I guess what could happen is that the robot can only point to an object with unknown name even if the actual highest saliency (and thus the gaze) is for another object. So without any goal, or with the goal of learning, the saliency should be increase to unknown object for instance?  

Another solution as you suggested Gregoire can be to change directly the saliency of an object when you have a precise behavior, but in that case it is similar to Ugo proposal to have a module "taking over" or "ignoring" the saliency when you have to do something specific. It is more clean in a coding way (the only module that change the saliency is the module that is actually suppose/design/responsible for the saliency), maybe a bit more weird in a "cognitive" way. An hybrid solution might be to have the module sending a command to `pasar` to increase greatly the saliency in an instant manner but this can not guarantee I guess an 100% "succes/consistent" gazing.

**Comment by stephane-lallee** [comment]
In the view I had back in the days, increasing this saliency based on a top-down symbolic information (an object is pointed at) would have been the role of Pasar.
Of course I do agree with Ugo that putting saliency information in the ARE subsystem is a terrible idea 😉

From a more conceptual point of view, isn't there something wrong in increasing the saliency of an object you are pointing at? If somebody else is pointing I agree but if it is yourself... I would say there is there some process similar to the inhibition of return that would actually decrease the saliency of the pointed object.

My suggestion would be : Point at the object, but loon at the agent to who you are showing the object. Because pointing is a communicative act...

And pointers are great. (was I not cleaning properly ?😉  )

-----Message d'origine-----
De : "maxime-petit" <notifications@github.com>
Envoyé : ‎23/‎02/‎2016 19:06
À : "robotology/wysiwyd" <wysiwyd@noreply.github.com>
Objet : Re: [wysiwyd] Run attention selector during proactive tagging (#42)

Gregoire you said that if you point to an object, its salience should increase, that is how you motivate ARE or subsystem_AREto be involved in the saliency. But for me it is actually the opposite: you point an object because the saliency is already high. The saliency cause your pointing, so the saliency should be high BEFORE you do the pointing: that is why you point this precise object and not another one. The pointing of another agent however, cause the saliency.
In proactive, I guess what could happen is that the robot can only point to an object with unknown name even if the actual highest saliency (and thus the gaze) is for another object. So without any goal, or with the goal of learning, the saliency should be increase to unknown object for instance? 
Another solution as you suggested Gregoire can be to change directly the saliency of an object when you have a precise behavior, but in that case it is similar to Ugo proposal to have a module "taking over" or "ignoring" the saliency when you have to do something specific. It is more clean in a coding way (the only module that change the saliency is the module that is actually suppose/design/responsible for the saliency), maybe a bit more weird in a "cognitive" way. An hybrid solution might be to have the module sending a command to pasar to increase greatly the saliency in an instant manner but this can not guarantee I guess an 100% "succes/consistent" gazing.

**Comment by clement-moulin-frier** [comment]
We are going to try this:
In `proactivetagging`, increase the saliency of the pointed object as well as the human agent, so that the robot gaze switch between both (like an infant would do actually). Can you confirm that we have to use Pasar for this? Or can we mor simply modify the saliency value using OPCClient?

Another question is: once the saliencies are modified, are they taken into account by Attention Selector? (i.e. does Attention Selector preferably look at the most salient object, or does it simply choose objects to look at them randomly?). 

@pattacini : can you please precise what connection we have to check?

Thx

**Comment by gregoire-pointeau** [comment]
You don't need to go through `pasar` to change the salience. `pasar` will change automatically according to the acceleration, pointing, waving and appearance disapperance.
Can you check that `pasar` works correctly? (go in front of the iCub with `agentDetector`, move and the salience of the agent should rise).

Then if you artificially increase the salience of an object, with `pasar` running it should decrease, but keep still if not.

**Comment by clement-moulin-frier** [comment]
Thanks. One problem is that even without Pasar running, the saliency is rapidly reset to 0 when the robot is pointing. Besides Pasar, do you know if there are other modules able to modify the saliency?

**Comment by gregoire-pointeau** [comment]
Any module that access the `OPC` can modify the salience. But I don't know other than `PASAR` that does.

**Comment by pattacini** [comment]
@clement-moulin-frier you could check that the following functions are actually called by putting some printouts within the code:
- [**`SubATT->stop()`**](https://github.com/robotology/wysiwyd/blob/master/main/src/libraries/wrdac/include/wrdac/subsystems/subSystem_ARE.h#L76)
- [**`SubATT->track()`**](https://github.com/robotology/wysiwyd/blob/master/main/src/libraries/wrdac/include/wrdac/subsystems/subSystem_ARE.h#L88)

**Comment by Tobias-Fischer** [comment]
Hi @clement-moulin-frier,
Have you further debugged this to see whether the attention system is called? We should figure this out before the integration meeting.

Best, Tobi

**Comment by clement-moulin-frier** [comment]
Hi @Tobias-Fischer 

We haven't figured out what is the reason of the saliency modification, see my last but one message (the long one).

**Comment by Tobias-Fischer** [comment]
Thanks to @pattacini and https://github.com/robotology/wysiwyd/pull/82 we got much closer to this goal. I suggest we sit together today and look for the reason why the saliency is reset to 0.0 as reported by @clement-moulin-frier.

I suggest we run the proactive tagging demo with `attentionSelector` and see how it goes.

Also @gregoire-pointeau should change `pasar` because of the slight position changes due to the vision changes, which lead to a too high saliency right now.

**Comment by jypuigbo** [comment]
Did this meeting take place? Which is the current status of the issue, after the integration? Thanks

**Comment by Tobias-Fischer** [comment]
From the debriefing email:
```
Progress towards running the attention selector during the demo was made. Objects now don't disappear when the iCub is looking to another object or the partner, previously leading the object to be set as not present in the OPC, as it was out of the field of view. However, we decided that for the year 2 demo we will not run attention selector, and do final tests before the year 3 review.
```

Thus, taking the high priority tag off. Let me know if you think otherwise @pattacini @gregoire-pointeau

**Comment by gregoire-pointeau** [comment]
Going from a boolean to 0 - 0.5 - 1 induce indeed many changes in the higher modules that for now are not taken into account and I agree we need more time to have some behaviors coherent with it.

**Comment by Tobias-Fischer** [comment]
Normal modules shouldn't check for the 0.5 value. That value is only meant to be used in `iol2opc` and `attentionSelector`, and @pattacini already took care of that.
However, I agree that there is now a difference of checking for == 1.0 vs != 1.0 vs == 0.0 which might have introduced new bugs we have to check again.

**Comment by gregoire-pointeau** [comment]
I don't totally agree with the fact that modules should check for 0.5, it depends of the behavior you want to have and this needs more time to think about that just a few weeks. For example in term of narrative, this induces many changes, and also in term of actions consequences for abmReasoning...
I agree however that it is an huge and useful improvement, but not as trivial at is seems for "higher" modules.

**Comment by pattacini** [comment]
@gregoire-pointeau when I introduced this change I payed particular attention to retain the old intended behavior in all the modules involved.

It should be straightforward to go through an exhaustive search for the flag `m_present` and do a double check.

**Comment by pattacini** [comment]
To recap:

The old check
```cpp
if (m_present)
```
should become
```cpp
if (m_present==1.0)
```

The old check
```cpp
if (!m_present)
```
should become
```cpp
if (m_present!=1.0)
```

**Comment by gregoire-pointeau** [comment]
Yes indeed in term of computation, it doesn't change much I agree, but if we want to take these changes into account and to use it, it won't be that trivial.
But in term of retro compatibility, I guess it doesn't change much indeed.

**Comment by pattacini** [comment]
I agree that for now we shouldn't employ this new piece of information for new devs.

**Comment by Tobias-Fischer** [comment]
@clement-moulin-frier @gregoire-pointeau @maxime-petit @pattacini 
Do you think this should be tackled in year 3?

**Comment by pattacini** [comment]
I have no objections to try it out again for year 3.

**Comment by maxime-petit** [comment]
Yes sure,

Maybe it does not have to be permanent but at least in some "subset" of scenario (like an active search, ...)

**Comment by clement-moulin-frier** [comment]
Would be a very good feature to have indeed. But we (upf) still haven't understood why and how the saliency decreases automatically (and very rapidly), preventing us to control it programatically in a robust way.
Does the new convention for `m_present`, now taking real values, change something?

**Comment by Tobias-Fischer** [comment]
I don't think anyone is planning to show this. Closing.
