### ISSUE TITLE
[iol2opc] Add options --empty and --nosave

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#60]
With similar behavior to the `objectsPropertiesCollector`.

This is a low priority issue.

**Comment by pattacini** [comment]
I've added the `--empty` option to `iol2opc` and it should work.

Conversely, the `--nosave` is tricky 'cause cannot be localized in just one place. As soon as the user stops the application, the modules can shut down independently and in a random order, thus not leaving any room for communicating that the `--nosave` process needs to be done.

I really don't like to spread this options among multiple modules and, further, I think it is not necessary in the end. Launching `iol2opc --empty` should be sufficient, since it's true that the database will be saved upon all the operations but then it will be cleared at start-up.

**Comment by Tobias-Fischer** [comment]
Great, thanks a lot Ugo! I didn't think about the issues regarding `nosave` and agree it would be too much hassle to implement.
I'll close this issue as soon as I tested the functionality of `empty` (probably in the new year).

Thanks, Tobi

**Comment by Tobias-Fischer** [comment]
Working perfectly, thanks!
