### ISSUE TITLE
Try SAM with OpenCV3

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#68]
See whether SAM still behaves the way it should using OpenCV3 (see https://github.com/robotology/wysiwyd/pull/67).

**Comment by Tobias-Fischer** [comment]
Hi @dcam0050, did you get a change to try this?

Thanks, Tobi

**Comment by Tobias-Fischer** [comment]
Any news @dcam0050?

**Comment by Tobias-Fischer** [comment]
@dcam0050: Can you please test this tomorrow so we can close this before the end of the integration meeting?

**Comment by Tobias-Fischer** [comment]
I'll try it one last time @dcam0050.

**Comment by Tobias-Fischer** [comment]
Closing as no one seems to care. Don't blame me if it's causing problems in the future ..

**Comment by pattacini** [comment]
I've just notified @dcam0050 via email.

**Comment by dcam0050** [comment]
Sorry @Tobias-Fischer  the last notifications you sent were sent to the now closed student email address I had. I sincerely apologise for this!

SAM with OpenCV3 will not be a problem for the integration meeting because we are currently not using vision driver which depends heavily on opencv2. I have noted this issue and when the time comes to resurrect that project will make sure everything works with opencv3.

So we can close this issue. Sorry again for the very late reply.
