### ISSUE TITLE
bodySchema launching problem with opencv

### ISSUE THREAD

**Issue by gregoire-pointeau** [robotology/wysiwyd#76]
Hi.
I updated opencv on the `icub-cuda` machine, but now, I have the following problem when I launch `bodySchema`:

```sh
icub@icub-cuda:~$ bodySchema
bodySchema: error while loading shared libraries: libopencv_videostab.so.2.4: cannot open shared object file: No such file or directory
```

But `iol2opc` works fine.
Do you know why it could have such a problem of `opencv` lib on the `icub-cuda`?

**Comment by Tobias-Fischer** [comment]
Hi,
why do you want to run `bodySchema`? This is an old module and was split: https://github.com/robotology/wysiwyd/tree/master/main/src/modules/bodySchema
Most likely, you want to run `babbling` (see `proactiveTagging.xml`).
The error occurs because the `bodySchema` executable which is still around is linked to an old version of OpenCV.

Best, Tobi

**Comment by gregoire-pointeau** [comment]
Okay nice.
I was trying all modules and I had a doubt about this one.
Ok, problem solved then.
