### ISSUE TITLE
Table with comparisons to other projects

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/wysiwyd#77]
We need to put the outcomes of https://github.com/robotology/wysiwyd/issues/55 https://github.com/robotology/wysiwyd/issues/59 https://github.com/robotology/wysiwyd/issues/57 https://github.com/robotology/wysiwyd/issues/56 https://github.com/robotology/wysiwyd/issues/54 https://github.com/robotology/wysiwyd/issues/53 together in tables showing the differences to WYSIWYD on one glance. We need to decide on the format of the table, and need to transfer the loosely written reports in these tables.

Best, Tobi

**Comment by sockchinglow** [comment]
I'm putting together the reviews into one document; I'll post follow-ups henceforth on the dedicated slack channel.

**Comment by Tobias-Fischer** [comment]
That's great news, thanks!

**Comment by sockchinglow** [comment]
The workload has been assigned/completed in the following manner.
[_CHRIS_](http://www.chrisfp7.eu/): Ugo
[_RoboHow_](https://robohow.eu/): Hyung Jin
_Cangelosi_: Tobias
[_POETICON(++)_](http://poeticon.csri.gr/): Maxime
[_ALEAR_](https://ikw.uni-osnabrueck.de/~neurokybernetik/projects/alear.html): Maxime
[_iTalk_](http://www.italkproject.org/): Jordi

Also included are some projects listed in the DoW.
[EFAA](http://efaa.upf.edu/project)
[JAMES](http://homepages.inf.ed.ac.uk/rpetrick/projects/james/)
[ROSSI](http://cadair.aber.ac.uk/dspace/handle/2160/553)
[CogX](http://cordis.europa.eu/project/rcn/86240_en.html)
[HUMANOBS](http://www.humanobs.org/)

I have posted the link to the table on slack, please refer to it. This is especially for the projects that you personally reviewed (@hjchang, @Tobias-Fischer, @maxime-petit,  @jypuigbo ), because some elements may be missing from the overview given and I might have misunderstood some details. Also, the other projects that were retrieved from the DoW needs a look-through.

@pattacini Still awaiting your review of CHRIS.

Lastly, STRAND was mentioned recently in the slack channel. Shall we include that as well?

**Comment by Tobias-Fischer** [comment]
Hi @sockchinglow,
Thanks, this is really helpful. Great.

Regarding STRAND, there is no need to include it.

@hjchang @maxime-petit @jypuigbo @pattacini: Please drop a quick message here after checking the table so we can close this issue.


Thanks,
Tobi

**Comment by pattacini** [comment]
Fine with me.

**Comment by hjchang** [comment]
All right!

**Comment by Tobias-Fischer** [comment]
Fine with me.

**Comment by Tobias-Fischer** [comment]
@maxime-petit @jypuigbo @pattacini: Can we close here?

**Comment by pattacini** [comment]
Yes, I think

**Comment by sockchinglow** [comment]
On @clement-moulin-frier's suggestion, I have added another two columns: Develops an autobiographical narrative; Learns to distinguish between the self and others.

Could contributors fill in those cells as well?

Also, it may be a good idea for us to reach a consensus regarding WYSIWYD's markups in particular.

**Comment by sockchinglow** [comment]
Everyone except @pattacini has yet to complete the extra columns. Would be good if it can be completed soon.
@Tobias-Fischer @jypuigbo @maxime-petit @hjchang

**Comment by Tobias-Fischer** [comment]
Hi, I've added some more stuff for Cangelosi + Poeticon++. However, I am not sure about some of the columns and left them empty rather than putting in false information. Would be good if someone else can have a look (maybe @maxime-petit?)

**Comment by Tobias-Fischer** [comment]
Hi @maxime-petit,
I saw you working on this yesterday. Did you finish it?
@jypuigbo @hjchang: Did you fill the table?

Best, Tobi

**Comment by jypuigbo** [comment]
Yes I did, if nothing changed :)

2016-04-06 18:30 GMT+02:00 Tobias Fischer <notifications@github.com>:

**Comment by Tobias-Fischer** [comment]
This should be done now. @sockchinglow: Do you want to send an email around to the WYSIWYD mailing list containing a link to the table and check that it's with with the PI's?

**Comment by Tobias-Fischer** [comment]
@sockchinglow: Please send this around to the mailing list ASAP!

**Comment by clement-moulin-frier** [comment]
I've just done it through the maillist `wysywid-project`

**Comment by Tobias-Fischer** [comment]
Thanks :)
